# Generated by Django 3.1.6 on 2021-02-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=50)),
                ('gender', models.CharField(choices=[('H', 'Hombre'), ('F', 'Mujer'), ('O', 'Otros')], max_length=1)),
            ],
        ),
    ]
