# Generated by Django 3.1.6 on 2021-02-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='libro',
            name='anio_edicion',
            field=models.CharField(default='NOFECHA', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='lugar_edicion',
            field=models.CharField(default='SIN LUGAR', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(1, 'NOVELA'), (2, 'ENSAYO')]),
        ),
    ]
