# Generated by Django 3.1.6 on 2021-02-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20210209_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(default=101010, upload_to='static/images_db'),
            preserve_default=False,
        ),
    ]
